# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=300, verbose_name='Телефон')),
                ('massages', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=300, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSiteTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.CharField(max_length=500, verbose_name='Телеграм пользователь')),
                ('partner_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.PartnerSite')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('url', models.URLField(verbose_name='Url сайта')),
            ],
        ),
        migrations.AddField(
            model_name='partnersite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Site'),
        ),
        migrations.AddField(
            model_name='logsite',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Partner'),
        ),
        migrations.AddField(
            model_name='logsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Site'),
        ),
    ]
